### ISSUE TITLE
macOS run init fail: thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups 

### ISSUE THREAD

**Issue by theowenyoung** [woodruffw/kbs2#370]
Hi, when I installed with cargo ,then run `kbs2 init`, show the following error:

```
hread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups at `[hash: BF680C65B3D91│~
2FE]`', /Users/green/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.6/src/parser/matches/arg_ma│~
tches.rs:1732:13                                                                                         │~
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by woodruffw** [comment]
Ugh, looks like `clap` changed its APIs underneath us. Thanks for the report, I can try to fix this now.

**Comment by woodruffw** [comment]
@theowenyoung Does this persist when you install the latest RC instead?

e.g.

```console
cargo install --force kbs2 --version 0.6.0-rc.1
```

**Comment by woodruffw** [comment]
Never mind, I was able to repro this even with the RC.

**Comment by woodruffw** [comment]
Clap seems to consider this a non-regression for their purposes: https://github.com/clap-rs/clap/issues/3826

**Comment by woodruffw** [comment]
#371 fixes the panics for me. I'll cut a new release candidate with it; let me know if you still have problems and I'll reopen.

(I also plan to do a full `0.6.0` release this week.)
