### ISSUE TITLE
`kbs2 edit` not working

### ISSUE THREAD

**Issue by jaredforrest** [woodruffw/kbs2#434]
There are 2 problems, the first is that `kbs2 edit` doesn't seem to work on cli editors (eg. vim, nano) and the second is that when I do manage to open it in an graphical editor the changes aren't saved. Also I'm running Linux (nixos).

**Comment by woodruffw** [comment]
Thanks for the report!

I can confirm that CLI editors aren't working correctly -- I'm unable to do `kbs2 edit foo` with `vim` as my configured editor. 

Graphical editors work for me locally, however (on both macOS and Linux). Which graphical editor did you try, and did you pass any additional flags?

**Comment by jaredforrest** [comment]
I only tried gedit before, I've now checked other editors and they seems to work. Also I found out what was causing the issue with cli editors. Essentially `output()` was taking control of `stdin` so `vim` couldn't access it.

**Comment by woodruffw** [comment]
Excellent, thanks for debugging that! I'll do a review of your PR this afternoon/evening.
